# Chapter 2: Regression and model validation  

In this exercise I analyze preprocessed data.  

###Link to preprocessing R script:  
<https://github.com/neabister/IODS-project/data/create_learning2014R>
  
###Link to original data:  

<http://www.helsinki.fi/~kvehkala/JYTmooc/JYTOPKYS3-data.txt>
  

###Original data and preprocessing  
Data is from Introduction to statistics course learning approaches study carried out in Helsinki 2014 and it is a part of multinational study. Approaches are defined by ASSIST guidelines and divided into three categories: Deep, Surface and Strategic study approaches. Students participated by filling in questionaires relating to these 3 approaches by answering 1-5 (least agreeing - most agreeing). In addition, data contains a measure for each student's attitude and achievements based on exam points.

In preprocessing, questions were divided into **Deep, Surface** and **Strategic** groups and for each group mean was calculated for each student. Analysis dataset includes additional information on gender, attitude and exam points. Students who had 0 points from exam were excluded.  

###Data analysis  

####Read the data and explore it  
```{r}
data <- read.csv('data/analysis_dataset.csv')
head(data)
dim(data)
str(data)

```
  
*Data contains 7 variables (columns) from 166 observations (students, rows). All variables are numeric or integers except gender which has 2 factors (female or male).*  

